# Generated by Django 4.1.2 on 2022-11-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
